services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - .:/workspace
    working_dir: /workspace/backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    depends_on:
      - db

  frontend:
    build: ./frontend
    # command: npm run dev -- --port 3001
    volumes:
      - .:/workspace
      - frontend_node_modules:/workspace/frontend/node_modules
    working_dir: /workspace/frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  db_data:
  frontend_node_modules:
