
services:
  backend:
    command: bash -c "bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"

  frontend:
    command: node --inspect=0.0.0.0:9229 node_modules/.bin/nuxi dev
    ports:
      - "9229:9229"  # デバッグ用ポート
